### ISSUE TITLE
allow in browser usage

### ISSUE THREAD

**Issue by MoOx** [Nyalab/caniuse-api#18]
it might sound silly, according to the database weight, but it would be nice to replace `require.resolve` usage by a json generation to avoid the readDir.
Probably hooked in the postinstall to have a json that match the installed db (so no prepublish since the json might be outdated according to the caniuse-db (hello semver)).
Also hooked in the "pretest" and it should be good.
Well it's almost done. I'll take a look to that tomorrow morning if nobody had done that before me.

**Comment by Nyalab** [comment]
Indeed, good solution for now, maybe ask "caniuse-db" later to be cleaner.
