### ISSUE TITLE
latest version of caniuse break current test

### ISSUE THREAD

**Issue by MoOx** [Nyalab/caniuse-api#19]
The diff for border-radius get support test now have a difference for `safari: { '#1': 6.1, x: 4, y: 3.1 }`.
Note the `#1` added. I take a quick look into recent caniuse db update and saw this diff https://github.com/Fyrd/caniuse/commit/44dc9c217ae1261fc81f8b1c961ee3d09c78b255

Do you just want me to add this for the test ?
Maybe we should make test simpler (no deep equal) and just test keys to avoid testing data (we don't need to test data right?)

**Comment by Nyalab** [comment]
I will change the way i test compat. For now it depends too much on fixed data. What i really need to test, is that i have to take data from raw files, transform it, and test if the output is correct. I will automatize that soon. But for now, yes, just look at real data, it will be enough. Thanks :sparkles:

**Comment by MoOx** [comment]
I've added a workaround in 90152c2872e4a9f3c70da693f1ca8dfc74cd5ffd to prevent issue _for now_ :).
Not sure why caniuse keeps only one entry for and_chr & and_ff...

**Comment by Nyalab** [comment]
Ok, i see, well, it works for now. Both of the browsers do not have the same rendering engine, so the both of them have to be tested.

**Comment by MoOx** [comment]
My point is that caniuse-db is just keeping one entry for those browsers. That's the weird part. Eg: https://github.com/Fyrd/caniuse/commit/41bd4f0c9a5d04996b1cd80299b6d7a9a0612447
