### ISSUE TITLE
Docker problems

### ISSUE THREAD

**Issue by mfrye** [Nyalab/caniuse-api#35]
So I realize that it is very vague but this module is causing me so many problems in trying to install with docker. It always seems to hang when it runs the generator.js and then crashes the process. Unfortunately I can't seem to get the error log out either. I saw there was another issue that mentioned the generator being a problem before, so I don't know if it's related or not.

I'm using the latest version of docker with node 4.2.2 and I'm running it on AWS free-tier.

**Comment by MoOx** [comment]
The generator was a problem probably because of an outdated shelljs version.
Are you using the latest version of this module?
You can also check shelljs if some bugfixes has been added compared to the version we are using atm.

**Comment by MoOx** [comment]
Closing due to no response.
