### ISSUE TITLE
postInstall step not running with JSPM

### ISSUE THREAD

**Issue by MeoMix** [Nyalab/caniuse-api#36]
Hey,

I saw another issue on this -- I'm encountering the same problem.

I install `cssnext` via jspm: `jspm install npm:cssnext`. It installs without error, but when I try to leverage cssnext I encounter an error stating that `features.js` does not exist.

If I navigate to the `caniuse-api` directory and run `node generator.js` the file is generated successfully and all is well.

Node v5.3.0
NPM v3.5.3
Windows 10 x64

**Comment by MoOx** [comment]
Does jspm run postinstall hook?
What output do you got when you install it? (you should got some logs from caniuse-api).

**Comment by tiagocpontesp** [comment]
Just leaving it here for reference https://github.com/jspm/npm/issues/36

**Comment by MoOx** [comment]
Does #41 fix this?

**Comment by MoOx** [comment]
Nvm I said shit.

**Comment by alexisvincent** [comment]
I'm having the same issue.

**Comment by alexisvincent** [comment]
After this mornings closed pull request, this is the only barrier to JSPM support

**Comment by MoOx** [comment]
See #42.

**Comment by MoOx** [comment]
Closed by #47
