### ISSUE TITLE
Issue if project folder have spaces in the path

### ISSUE THREAD

**Issue by mphillipss** [Nyalab/caniuse-api#39]
Attempting to install material-ui@0.13.3 on CentOS Linux release 7.2.1511 (Core) 
. I was successful yesterday (don't know how), but am now failing due to caniuse-api@1.4.1.

Using react 0.14.3 but believe material-ui attempts to upgrade to 0.14.7

Looking for suggestions

> npm ERR! Linux 3.10.0-327.10.1.el7.x86_64
> npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
> npm ERR! node v4.4.0
> npm ERR! npm  v2.14.20
> npm ERR! code ELIFECYCLE
> 
> npm ERR! caniuse-api@1.4.1 postinstall: `node generator.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the caniuse-api@1.4.1 postinstall script 'node generator.js'.
> npm ERR! This is most likely a problem with the caniuse-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node generator.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs caniuse-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! 
> npm ERR!     npm owner ls caniuse-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/npm-debug.log

> caniuse-api@1.4.1 postinstall /var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api
> node generator.js

> module.js:327
>     throw err;
>     ^

> Error: Cannot find module '/var/lib/jenkins/jobs/Arches'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:968:3
> shell.js: internal error
> Error: Command failed: "/usr/bin/node" /var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api/shelljs_61861a524f0a7dc03ee0
>     at checkExecSyncError (child_process.js:464:13)
>     at Object.execSync (child_process.js:504:13)
>     at execSync (/var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api/node_modules/shelljs/src/exec.js:81:11)
>     at _exec (/var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api/node_modules/shelljs/src/exec.js:214:12)
>     at /var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api/node_modules/shelljs/src/common.js:182:23
>     at Object.<anonymous> (/var/lib/jenkins/jobs/Arches - Development - Front/workspace/node_modules/material-ui/node_modules/inline-style-prefixer/node_modules/caniuse-api/generator.js:4:3)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)

**Comment by MoOx** [comment]
According to the error, which is `Error: Cannot find module '/var/lib/jenkins/jobs/Arches'`, not sure it's directly related...

Well, I may have an idea. Do you have a space in your folder '/var/lib/jenkins/jobs/Arches ...* ????' ?

**Comment by matthewjaymesphillips** [comment]
There is plenty of space in the folder; however, the directory is `/var/lib/jenkins/jobs/Arches - Development - Front/`and all other npm installations have no issue installing into it; but could the naming convention be an issue?

**Comment by mphillipss** [comment]
Removed `- `and `spaces` from directory name and had no issue. Please feel free to close this issue.

**Comment by MoOx** [comment]
Not it's a bug of this module. Will fix.

**Comment by mphillipss** [comment]
Okay - Happy Fixing!

**Comment by MoOx** [comment]
Should be closed by #47 since there is no generation step anymore. Feel free to ping here if this problem happen again.
