### ISSUE TITLE
1.6.0 is listed as an available version but does not exist in npm

### ISSUE THREAD

**Issue by tquetano-r7** [Nyalab/caniuse-api#58]
Per npm view it appears that on 4-6 version 1.6.0 was published ... but the next day 1.6.1 was published, and version 1.6.0 was unpublished or something? Even though the version exists in npm view it is no longer in the tree of available tgzs, so I'm making a guess here. (https://registry.npmjs.org/caniuse-api)

Problem is ... this causes yarn to blow up, because someone somewhere listed 1.6.0 as a valid dependency. I imagine you unpublished it for good reason (horrible problems or something), but would you mind publishing 1.6.1 again as 1.6.0 or something? I know the "right" thing would be to find the package and have them update their dependencies to be correct, but this should also be done (unpublishing is bad news).

**Comment by MoOx** [comment]
If it has been published, I am not sure you can publish again.

**Comment by tquetano-r7** [comment]
Crap ur right ... https://docs.npmjs.com/cli/unpublish.

**Comment by tquetano-r7** [comment]
Edit: nvm, killing the `yarn.lock` did it. Closing, but please don't `unpublish` again if possible. Cheers!
