### ISSUE TITLE
1.6.0 is no longer found in registry

### ISSUE THREAD

**Issue by beeleebow** [Nyalab/caniuse-api#72]
Our build starting failing this morning because we could not yarn install 1.6.0 of caniuse-api. Has this been removed from the public registry?

![caniuse-api-1 6 0-not-found](https://user-images.githubusercontent.com/5163176/36573086-ddc174dc-188a-11e8-98e0-4d86fdaba2d3.png)

**Comment by MoOx** [comment]
We never made a 1.6.0 https://github.com/Nyalab/caniuse-api/releases https://github.com/Nyalab/caniuse-api/blob/master/CHANGELOG.md

**Comment by beeleebow** [comment]
Hmmm. That is definitely weird. Build worked yesterday and failed today because it couldn't pull 1.6.0. Also, it shows up as a version on the yarn page. It says it was released on the same date as 1.6.1 (April 7 2017).

https://yarnpkg.com/en/package/caniuse-api
![yarn-page-version](https://user-images.githubusercontent.com/5163176/36591254-1f8d6388-18dd-11e8-80ae-e94f21c949aa.png)

**Comment by MoOx** [comment]
If my memory is correct it has been removed immediately.
Btw it's impossible to unpublish from npm after 24h.

**Comment by beeleebow** [comment]
Weird. I have no explanation for how this happened. But it's irrelevant I guess. If it doesn't exist, that's that. Anyway, thanks for the response.
