### ISSUE TITLE
Add ignoreUnknownVersions option

### ISSUE THREAD

**Issue by ai** [Nyalab/caniuse-api#79]
You need just pass this option to Browserslist. It is very important to fix cssnano issue

https://github.com/cssnano/cssnano/issues/537

**Comment by Nyalab** [comment]
thanks, we had the same idea, i already put it in the [3.0.0](https://github.com/Nyalab/caniuse-api/commit/3ab3a830a97807e2a5b4013fa7d621ab5011192a#diff-1fdf421c05c1140f6d71444ea2b27638R47) release
